### ISSUE TITLE
FPKI Guide: Activity Report Table Update

### ISSUE THREAD

**Issue by ryancdickson** [GSA/playbooks-wdsv2#117]
In the update to the new site, HTML color formatting no longer conveys to the FPKI Activity Report (https://playbooks.idmanagement.gov/fpki/tools/fpkiar/).

The issue could be due to the use of DIV tags within the HTML file (we've seen issues with DIV tags on the System Notifications / Announcements pages).

**Comment by idmken** [comment]
Converted to markdown tables.
