### ISSUE TITLE
Sort FICAM Playbooks By Date

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#151]
#### Description of Issue: ####
Nice to be able to sort FICAM Playbooks by date.

https://playbooks.idmanagement.gov/playbooks/

**Comment by maxwellfunk** [comment]
I think this will require use of a javascript:
https://www.w3schools.com/howto/howto_js_sort_table.asp

**Comment by idmken** [comment]
Other tables for sorting and filtering.
- https://playbooks.idmanagement.gov/fpki/tools/
- https://playbooks.idmanagement.gov/fpki/announcements/
- https://playbooks.idmanagement.gov/fpki/notifications/
- https://playbooks.idmanagement.gov/playbooks/

**Comment by idmken** [comment]
fixed #261
