### ISSUE TITLE
Content Signing Cert Info in PIV Guide

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#160]
I can't find information about the content signing certificate in the PIV guide. Expecting to see it here - https://playbooks.idmanagement.gov/piv/details/

**Comment by ryancdickson** [comment]
Whereas [800-73-4](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-73-4.pdf) calls out specific containers for PIV Auth, Card Auth, Dig Sig, and Key Management Certificates (and Windows can interpret these containers natively - and you can observe them all through certmgr.msc) --- the same is not true for the Content Signer. Also, unlike these other certificates, the Content Signer is not unique to the cardholder. 

It's most likely you'll only encounter the content signing certificate as it's been used to sign other objects on the card (like in the optional Secure Messaging Container).  With that in mind, most cardholders will never know it exists. 

If you're interested in checking out your content signing certificate, I'd recommend using the [Card Conformance Tool](https://github.com/GSA/piv-conformance) to export the certificate object.

If you'd like some content related to the content signer on the PIV Details page, let me know!

**Comment by maxwellfunk** [comment]
could just be a note on an additional cert that cannot impact the user but might impact PACS

**Comment by maxwellfunk** [comment]
draft verbiage included in the 617 update branch
