### ISSUE TITLE
OpenSC 0.20.0 required for TLS 1.3

### ISSUE THREAD

**Issue by grandamp** [GSA/playbooks-wdsv2#196]
**Describe the bug**
The PIV playbook does not recommend a minimum version of OpenSC 0.20.0.

If a version of OpenSC less than 0.20.0 is used, users will encounter errors when performing mTLS with servers that offer TLS 1.3.

**To Reproduce**
1. Install a version of OpenSC less than 0.20.0
2. Configure Firefox according to: https://github.com/GSA/ficam-playbooks/blob/staging/_piv/engineer/01_firefox.md
3. Navigate to this test site:  https://caia-dev.treasury.gov/oidcServletdemo/
4. Select "Login (Servlet Callback)"
4. Select "PIV/CAC" button to authenticate

**Expected behavior**
Successful mTLS via x509-dev.treasury.gov

**Observed behavior**
TLS/Browser error received

**Desktop (please complete the following information):**
 - OS: All
 - OpenSC Versions prior to 0.20.0

**Additional context**
OpenSC did not support RSA-PSS signatures prior to 0.20.0:  https://github.com/OpenSC/OpenSC/pull/1435

RSA-PSS signatures are needed for TLS 1.3, in contrast to PKCS1v1.5 signatures.

We have also observed this defect with xTec AuthentXware versions prior to 3.01.43, where Chrome will return the error "ERR_SSL_CLIENT_AUTH_SIGNATURE_FAILED".

**Comment by idmken** [comment]
Thanks @grandamp schedule this in the next sprint.
