### ISSUE TITLE
Document PIV/PIV-I Card Testing Submission Requirements

### ISSUE THREAD

**Issue by ryancdickson** [GSA/playbooks-wdsv2#197]
Create a page associated with the [Card Conformance Tool](https://playbooks.idmanagement.gov/fpki/tools/cpct/) page to outline what testing artifacts are required for evaluation.

We currently provide this level of detail via email, but it'd be easier (operationally) to just reference the Playbook.

**Comment by maxwellfunk** [comment]
same as issue #236

**Comment by maxwellfunk** [comment]
closing due to linked issue above
