### ISSUE TITLE
Federation Test Steps

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#204]
Good content from Identiverse to include in SSO playbook.

https://identiverse.gallery.video/detail/videos/architecture-deployment/video/6186098604001/troubleshooting-federation-issues-on-the-wire---supporting-technologies-through-protocol-analysis?autoStart=true&page=1

When you get a federation error:
1. Test a known good app.
2. Check SSO and application logs.
3. Check network routing
4. Check Certificates
5. Check application configuration
6. Collect assertion data and use assertion analysis tools.

**Comment by rsherwood-gsa** [comment]
Okay to add this to the 917-playbook-sso branch, or should I create a sub-branch under that?

**Comment by JillTunick** [comment]
I'm guessing the branch itself; that's where Max had me do the issue #198
changes.

Jill Tunick
***@***.***
Supporting GSA FICAM Playbooks
CertiPath, Inc.
(703) 855-3124

**Comment by rsherwood-gsa** [comment]
@idmken I have made updates to the playbook in the 917 branch to incorporate this recommendation. High level, but a pointer for administrators to dig in more. We can further expand if you think it would be helpful.
