### ISSUE TITLE
DIRA Playbook Update - Determining Risk Level Independent from Credential Levels

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#205]
Include a practice note that results of a DIRA do not change established credential processes. Just that various credentials at a level can be used (e.g. if a DIRA arrives at IAL2, this allows use of IAL2 but does not change the requirement of downgrading an IAL3 process to an IAL2).

**Comment by JillTunick** [comment]
I inserted the note in a Key Point box at the end of Step 2 in the DIRA migration markdown page
(https://github.com/GSA/ficam-playbooks/blob/DIRA_migration/_playbooks/DIRA_intro.md)

**Comment by JillTunick** [comment]
I uploaded an updated PDF in the 920-playbook-dira-update/docs repo. The updated PDF includes the Key Point box added at the end of Step 2 in the DIRA md page.
