### ISSUE TITLE
Create section on Path Discovery and Validation to supplement FPKI

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/playbooks-wdsv2#208]
#### Description of Issue: ####
Although there is current guidance on trust stores, it may be valuable to potential readers to provide details about path discovery and validation (to potentially include concepts like certificate status services, and more obscure topics like link certs, etc.)

This issue replaces a similar one about SCVP

#### References (Docs, Links, Files): ####
RFC5280

#### Possible Solution ####
Develop a new section under FPKI or PIV guides that speaks to PDVAL

#### If a New Page or Content is Needed, Expected Outcomes: ####
Provides a reader common functions of PDVAL according to 5280 and some of the known pain points.

**Comment by maxwellfunk** [comment]
taking place of issue #88

**Comment by grandamp** [comment]
Let me know how I can help!

**Comment by idmken** [comment]
You could check the MA guide on trust store management as a start point.

**Comment by maxwellfunk** [comment]
content drafted, currently migrating to playbooks repo in its own branch:
https://github.com/GSA/ficam-playbooks/tree/PDVAL

**Comment by maxwellfunk** [comment]
Content drafted and currently in review with a handful of final coding fixes:
https://federalist-db14ea61-37f0-44fd-8ab9-591433f0ec2b.app.cloud.gov/preview/gsa/ficam-playbooks/PDVAL/fpki/pdval/#how-are-paths-built
