### ISSUE TITLE
System Notification for: DigiCert Symantec SSP Intermediate CA G4 and G5

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#220]
Subect: FPKI System Notification - MPKI 8 - Symantec SSP Intermediate CA - G4 and G5

Notice Date: 8/9/2021

Change type: CA Migration

Change Start Date: 7/30/2021

Change End Date7/30/2021

Change Description: Intermediate CAs were moved from a legacy system to a new one, and an old admin rule from our Verizon hosted CDN was overwriting internal settings and causing CRLs to go stale and not be refreshed at the required cadence.

Contact Email: fpki_support@digicert.com

If change is new or revoked CA, include CA Cert Hash, Issuer and Subject DN’s

            ICA Name: Symantec SSP Intermediate CA - G4 

            Serial: 26 2B D1 F0 25 C8 AF 37 33 45 45 66 6E A6 C9 EA 94 6C 2C 34

            Issuer: U.S. Government

            ICA Name: Symantec SSP Intermediate CA - G5

            Serial: 26304

            Issuer: U.S. Government

**Comment by maxwellfunk** [comment]
I created a notification to cover both of these on 8/2 via the outage.  Since this is in the past not sure if it is helpful as a notification post outage.

**Comment by maxwellfunk** [comment]
closing for early august system notification.
