### ISSUE TITLE
fpki-x509-cert-policy-fbca.pdf moved; 404 broken link

### ISSUE THREAD

**Issue by guidolotito** [GSA/playbooks-wdsv2#230]
**Describe the bug**
I had saved this link: https://www.idmanagement.gov/wp- content/uploads/sites/1171/uploads/fpki-x509-cert-policy-fbca.pdf

**To Reproduce**
1. Go to https://www.idmanagement.gov/wp- content/uploads/sites/1171/uploads/fpki-x509-cert-policy-fbca.pdf
2. Get 404, not the document

**Expected behavior**
That link used to take me to the document

**Screenshots**
Not necessary

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Big Sur
 - Browser [e.g. chrome, safari] Safari
 - Version [e.g. 22] 14.1.2

**Comment by JBPayne007** [comment]
You can now find this document at the bottom of this site.
https://playbooks.idmanagement.gov/fpki/

**Comment by idmken** [comment]
@guidolotito Thanks! We've migrated idmanagement.gov material to a new host. 

This exact document link is now - https://www.idmanagement.gov/docs/fpki-x509-cert-policy-fbca.pdf

The page to find the document is now - https://www.idmanagement.gov/governance/fpkiaudit/
