### ISSUE TITLE
CCT expanded instructions

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/playbooks-wdsv2#236]
#### Description of Issue: ####
Need to expand CCT page under the FPKI playbooks page to include instructions for submitting testing packages to the FIPS 201 EP for analysis and report generation.

#### Details of Issue: ####
We are currently receiving incomplete remote PIV and PIV-I testing packages from PKI entities.

#### References (Docs, Links, Files): ####
https://playbooks.idmanagement.gov/fpki/tools/cct/ 

#### Possible Solution ####
Initially expand the linked page above to include instructions of what to include in a submission package.

#### If a New Page or Content is Needed, Expected Outcomes: ####
appropriate level of detail for the FIPs 201 EP team to generate a report.

**Comment by idmken** [comment]
Fixed #267
