### ISSUE TITLE
FICAM Architecture Standards link reference

### ISSUE THREAD

**Issue by sarahdobson** [GSA/playbooks-wdsv2#26]
#### Description of Issue: ####
FICAM Architecture Standards & Policies

https://federalist-6b49c9d3-af36-4c09-9954-7421ffabc251.app.cloud.gov/preview/gsa/playbooks-wdsv2/staging/arch/standards/#policies

OMB Circular A-123 points to M-16-17

#### Details of Issue: ####
The link to OMB Circular A-123 points to the document with M-16-17 as a cover page. Should we reference M-16-17 in the link text or context paragraph?

#### Link to the Content Page for Contributors: ####
https://github.com/GSA/playbooks-wdsv2/blob/staging/_arch/ficam_standards_policies.md

**Comment by idmken** [comment]
It looks like OMB A-130 is M-16-17. Include M-16-17 in the title for it. "OMB Memo 16-17 - Circular A-123....

**Comment by idmken** [comment]
Added to sprint branch.
