### ISSUE TITLE
PM Playbooks Stakeholder page might need a link update

### ISSUE THREAD

**Issue by sarahdobson** [GSA/playbooks-wdsv2#37]
The link to Suitability and Security Clearance Performance Accountability Council (PAC) might lead to the wrong page: https://www.dcsa.mil/About/

Potential new link: https://www.gao.gov/highrisk/govwide_security_clearance_process/

**Comment by maxwellfunk** [comment]
The DCSA might be the evolution of the PAC, in which case we might need to update the title.

**Comment by idmken** [comment]
I can not find if the PAC has an actual web page. The old link was to the OPM National Background Investigations Bureau (NBIB) which was transferred to the DoD Defense Counterintelligence and Security Agency (DCSA). This explains the redirect. 

In researching an updated link. The PAC does not seem to have a dedicated website. A Security, Suitability, and Credentialing Line of Business (SSCLoB) still exists within OPM (also no website) to support the Security, Suitability, and Credentialing Performance Accountability Council (PAC) through a Program Management Office (PAC PMO) (also no website).

There was a reform effort under the Trump Administration -https://trumpadministration.archives.performance.gov/CAP/security-clearance-reform/, but is not yet identified as a goal under the current administration.

Resolution - Removing link and closing issue.

**Comment by idmken** [comment]
Added to Sprint Branch to merge.

**Comment by idmken** [comment]
Added to sprint branch for merge.
