### ISSUE TITLE
Update PIV Logon Troubleshooting to link common errors to remediation steps

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#471]
#### Description of Issue: ####
There are other logon errors that should get added to the troubleshooting page. https://playbooks.idmanagement.gov/piv/network/troubleshooting/

#### Details of Issue: ####
1. The system could not log you on. Your credentials could not be verified.
2. Signing in with a Smart Card Isn't Supported for Your Account

#### References (Docs, Links, Files): ####
http://download.mysmartlogon.com/SmartPolicyv2/Troubleshooting%20smart%20card%20logon%20authentication.pdf

#### Possible Solution ####
Update the troubleshooting page to include these two errors.

#### Link to the Content Page for Contributors: ####
https://playbooks.idmanagement.gov/piv/network/troubleshooting/

**Comment by JillTunick** [comment]
We have assigned this issue to the SME who wrote the Troubleshooting PIV Logon page.
