### ISSUE TITLE
Update AltSecID to address how to get certificates

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#472]
#### Description of Issue: ####
The Account Linking page which talks about how to change an AD configuration to use AltSecID does not mention how to gather the certificates to load into AD. There is a script in how to automate the AD updated but not how to gather the certificates.

https://playbooks.idmanagement.gov/piv/network/account/

#### Possible Solution ####
Include this as a step and provide suggestions on how to either gather or access a cert database.

#### Link to the Content Page for Contributors: ####
https://playbooks.idmanagement.gov/piv/network/account/

**Comment by JillTunick** [comment]
We have assigned this issue to an SME.
