### ISSUE TITLE
Promulgate CISA guidance on Cert Based Auth fixes

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/playbooks-wdsv2#565]
#### Description of Issue: ####
CISA guidance on short term resolutions for barriers to certificate based authentication within Microsoft products needs to be promulgated via the PIV playbook.

#### Details of Issue: ####
Microsoft May patching has disrupted certificate based authentication based on use of weak identifiers mapped to network accounts (e.g., UPN).  

#### References (Docs, Links, Files): ####
https://support.microsoft.com/en-us/topic/kb5014754-certificate-based-authentication-changes-on-windows-domain-controllers-ad2c23b0-15d8-4340-a468-4d4f3b188f16

#### Possible Solution ####
Create an alert callout at the top of the PIV network login page to introduce the guidance and link to the recommended fixes

cyberliaison@cisa.dhs.gov

#### Link to the Content Page for Contributors: ####
https://playbooks.idmanagement.gov/piv/network/

**Comment by idmken** [comment]
New guidance published - https://www.cisa.gov/guidance-applying-june-microsoft-patch
