### ISSUE TITLE
System Notification for: <Your Organization>

### ISSUE THREAD

**Issue by NZCommanderPRO** [GSA/playbooks-wdsv2#580]
notice_date: 
change_type:  CA Certificate Issuance, CA Certificate Revocation, New CA, URI Change, System Outage 
start_datetime: 
end_datetime: 
system: 
change_description: 
contact: 
ca_certificate_hash: 
ca_certificate_issuer: 
ca_certificate_subject: 
cdp_uri: 
aia_uri: 
sia_uri: 
ocsp_uri:

**Comment by grandamp** [comment]
Where is the info for this submission, and whom is it for?
