### ISSUE TITLE
Broken link in Common Policy X.509 Certificate and  Certificate Revocation List (CRL) Profiles

### ISSUE THREAD

**Issue by rsherwood-gsa** [GSA/playbooks-wdsv2#602]
#### Description of Issue: ####
The Common Policy X.509 Certificate and Certificate Revocation List (CRL) Profiles document contains a link to the X.509 Certificate and Certificate Revocation List (CRL) Extensions Profile for Personal Identity Verification Interoperable (PIV-I) Cards. However, the URL in the document leads to a 404.

#### Details of Issue: ####
The URL in the Common Policy X.509 Certificate and Certificate Revocation List (CRL) Profiles document is: https://www.idmanagement.gov/wp-content/uploads/sites/1171/uploads/fpki-x509-cert-profiles-pivi.pdf

The correct URL for this document is:
https://www.idmanagement.gov/docs/fpki-x509-cert-profiles-pivi.pdf

#### References (Docs, Links, Files): ####
Link to Common Policy X.509 Certificate and Certificate Revocation List (CRL) Profiles document: https://www.idmanagement.gov/docs/fpki-x509-cert-profile-common.pdf

#### Possible Solution ####
Update document to include correct link.

#### If a New Page or Content is Needed, Expected Outcomes: ####
N/A

#### Link to the Content Page for Contributors: ####
[Common Policy X.509 Certificate and Certificate Revocation List (CRL) Profiles document](https://www.idmanagement.gov/docs/fpki-x509-cert-profile-common.pdf)

**Comment by maxwellfunk** [comment]
Once FBCA profiles are updated we will need to completely remove PIV-I profiles from all remaining documents.  Common probably shouldn't even reference PIV-I profiles anymore since it has sperate common pivi profiles.

**Comment by claytonjbarnette** [comment]
Updated link to PDF in PDF file: `/docs/fpki-x509-cert-profile-common.pdf`
- Archived and removed original
- Upload new version of file
- Submitted PR: [0826-issue-602 #217](https://github.com/GSA/idmanagement.gov/pull/217)

**Comment by maxwellfunk** [comment]
We will be presenting a change to the Common Profiles in the September so we maybe overwriting this version number once approved.

@rsherwood-gsa note that this issue was in the wrong repo, the foundational FPKI docs are on idmanagement.gov repo not playbooks.

@claytonjbarnette please be aware that foundational FPKI documents cannot be updated without the approval of the PA itself or the co-chairs.  Please coordinate these doc changes with our team prior to working any changes as we can get you the source editable documents.

**Comment by maxwellfunk** [comment]
@idmken recommend we close this issue as the profile documents will both be updated within a month or two anyway.
