### ISSUE TITLE
Wrong version and date for FICAM Playbooks

### ISSUE THREAD

**Issue by claytonjbarnette** [GSA/playbooks-wdsv2#631]
The following Playbook's version and date do not match the revision history date/version.
- [https://playbooks.idmanagement.gov/playbooks/sso/](https://playbooks.idmanagement.gov/playbooks/sso/)
  - in Playbook and Table. It should be November 16, 2021 and 2021-11, respectively.
 - [https://playbooks.idmanagement.gov/playbooks/dw/](https://playbooks.idmanagement.gov/playbooks/dw/)
   - in Playbook and Table. It should be November 18, 2021 and 2021-11, respectively.
- [https://playbooks.idmanagement.gov/playbooks/dira/](https://playbooks.idmanagement.gov/playbooks/dira/)
  -  in Playbook and Table. It should be November 17, 2021 and 2021-11, respectively.
 - [https://playbooks.idmanagement.gov/playbooks/signfedregister/](https://playbooks.idmanagement.gov/playbooks/signfedregister/)
   - reflects no date in playbook but 2018-07 in table 
   - (Note: This is the playbook was updated per issue 211)
- [https://playbooks.idmanagement.gov/playbooks/signword/](https://playbooks.idmanagement.gov/playbooks/signword/)
  -  reflects no date in playbook but 2018-03 in table

###  Possible Solution 

Update date and version information in the front matter of each Playbook, this change should also reflect in the listing as well for each playbook once updated.  

---
The FICAM Playbooks table locations:  
- Playbooks Listing: [https://playbooks.idmanagement.gov/playbooks/](https://playbooks.idmanagement.gov/playbooks/)

**Comment by JBPayne007** [comment]
These have been updated.
