### ISSUE TITLE
Footer Update for FICAM Playbooks

### ISSUE THREAD

**Issue by claytonjbarnette** [GSA/playbooks-wdsv2#632]
#### Playbooks footer: 

The text of footer link titles do not exactly match the text of the pages they link to but are in the right ballpark. 

- **Accessibility support** goes to [Accessibility Aids](https://www.gsa.gov/website-information/accessibility-aids)
- **Performance reports** takes the user to [Budget & Performance](https://www.gsa.gov/reference/reports/budget-performance) 
- Change `“Office of the Inspector General”` to *“Office of Inspector General”* (no `“the”`)

#### Possible Solution

- Adjust text in `footer.html`  to correct the footer for the entire site, and links should be updated to reflect the title of the page it is linked to. 

#### Location: 

[https://playbooks.idmanagement.gov/](https://playbooks.idmanagement.gov/)

**Comment by JBPayne007** [comment]
Please make these corrections.

**Comment by claytonjbarnette** [comment]
@JBPayne007 WIP...

**Comment by idmken** [comment]
This is a standard footer used across all of GSA. Unfortunately, we can't deviate from it.
