### ISSUE TITLE
Corrections and Link updates for Federal ICAM Architecture Page

### ISSUE THREAD

**Issue by claytonjbarnette** [GSA/playbooks-wdsv2#633]
#### Description of Issue: ####

Textural and Grammar updates

#### Details of Issue: ####

- ✅  In Introduction **sidenav** (bottom of section) an _incorrect title used_.
  - Change: “What Is the History of the FICAM Architecture Background?”
  - ✔️ To: “What Is the History of the FICAM Architecture?” 
- ✅ On the _"Services Framework-Access Management,"_ **sidenav,**  under _“Access Management”:_
  - **Change:** the reference to _“see the application inventory section of the Single Sign-On Playbook”_. 
  - ✔️  **To:** **“see the Application Inventory and Identity Risk Analysis section of the Enterprise Single Sign-On Playbook”** so it matches the heading 2.1 on the linked page you see, after following the link to: [here](https://playbooks.idmanagement.gov/playbooks/sso/#step-2-plan-application-integration)
- ✅ [In Use Case](https://playbooks.idmanagement.gov/arch/usecases/) 2 [+]:
    -  ✔️  The link associated with hyperlinked _NIST SP 800-63-A_ goes to a general table at [https://pages.nist.gov/800-63-3/](https://pages.nist.gov/800-63-3/) not to the specific document.
    - ✔️ Also, there should not be a hyphen between _63_ and _A (NIST SP 800-63A)_  
- ✅ [In Use Case](https://playbooks.idmanagement.gov/arch/usecases/) 4 [+]:
  -  ✔️ the link associated with hyperlinked NIST SP 800-63-B goes to a general table at https://pages.nist.gov/800-63-3/ not the specific document. 
  - ✔️ Also, change _NIST SP 800-63-B_ to **NIST SP 800-63B**. 
> ℹ️  Note: In Use Case 7 the link to _NIST SP 800-63B_ goes directly to Section 5 of that document, not the table. This is the practice mostly followed. 
> *For subsections (`ex: 2.2`), I had to use the full element id name instead of version number*
- ✅ Links in [Standards and Policies](https://playbooks.idmanagement.gov/arch/standards/) have issues: (They are inconsistent and need editing.)
  -  ✔️  [Under “Laws,](https://playbooks.idmanagement.gov/arch/standards/#laws)” 
     - 👍 The link for Privacy Act of 1974 actually goes to Freedom of Information Act although the Privacy Act is mentioned in five places in the PDF. 
     - ✔️ The link to FISMA doesn’t go to actual act. It goes to GovInfo where a PDF can be accessed
     - ✔️ Same issue with Government Paperwork Elimination Act. The act appears many pages into the hyperlinked document. Should link to actual page where act begins.
- 👍 [Under “Policies,](https://playbooks.idmanagement.gov/arch/standards/#policies)” within **M-15-13** entry, the link to “The Compliance Guide: HTTPS-Only Standard” goes well within document to a page of unclear reference.
- ✅ [Under “Standards,](https://playbooks.idmanagement.gov/arch/standards/#standards)”
  - ✔️  links for _NIST SP 800-16 R, NIST SP 800-63-3, NIST SP 800-63A, NIST SP 800-63B, NIST SP 800-63C, NIST SP 800-73-4, NIST SP 800-79-2, NIST SP 800-53 Rev. 5, NIST SP 800-53A Rev. 4, NIST SP 800-157, NIST SP 800-162, NIST SP 800-76-2 and NIST SP 800-122_ are not direct links to the document. They take you to site where the document can be downloaded.
  - ✔️ [FIPS 201-2](https://playbooks.idmanagement.gov/arch/standards/#standards) has been superseded by FIPS 201-3. Need to link to _FIPS201-3_. Again, not a direct link to the document.
- ✅ [Under Additional Resources](https://playbooks.idmanagement.gov/arch/standards/#additional-resources)
  - ✔️ NIST FISMA Implementation Project: Risk Management Framework Overview: The link is not to the named document. I only see something to do with FISMA under “Additional Pages.” The listed Resource likely should be NIST SP 800-37 Rev. 2 Risk Management Framework.
  - 👍 NIST SP 800-63 FAQs: Looks like the document date should be March 2022.
  - 🔍 NIST Privacy Framework is not a direct link, however, the document can be accessed from this location.
  - ✔️ NIST White Paper (White Paper NIST CSWP 4) is not a direct link to the document, however, the document can be accessed from this location.
  - 👍 Application Rationalization Playbook shows a June 2019 date, but the actual document reflects version 1.1 but no date.

#### Possible Solution 

Update links and text where needed. 

#### Link to the Content Page for Contributors: ####
[https://playbooks.idmanagement.gov/arch/](https://playbooks.idmanagement.gov/arch/)

**Comment by JBPayne007** [comment]
Please make these corrections.

**Comment by claytonjbarnette** [comment]
@JBPayne007 WIP

**Comment by claytonjbarnette** [comment]
@JBPayne007 updating this issue with markers. 
- 👍 Page link correct and in context or web page resource only (no direct file)
- ✅ Sections complete
- ✔️ Item complete
- 🔍 Need help locating resource
