### ISSUE TITLE
Updates for the Federal Public Key Infrastructure Page 

### ISSUE THREAD

**Issue by claytonjbarnette** [GSA/playbooks-wdsv2#634]
#### Description of Issue:

Link text updates needed to match the link's destination page titles. 

#### Details of Issue: 

- Under “[Where Can I Find the Policies and Standards?](https://playbooks.idmanagement.gov/fpki/#where-can-i-find-the-policies-and-standards)”
  -  **The second bullet:** title varies from the actual document title: Common Policy X.509 Certificate and Certificate Revocation List (CRL) Profiles NOT X.509 Certificate and CRL Profiles for the U.S. Federal PKI Common Policy Framework
  - **Fourth bullet:** goes to “Federal Public Key Infrastructure (PKI) X.509 Certificate and CRL Extensions Profile” but text says “X.509 Certificate and CRL Extensions Profile for the FBCA”
  - **Fifth bullet:** Full title is NOT reflected in the bullet text. Full title is "X.509 Certificate and Certificate Revocation List (CRL) Extensions Profile for Personal Identity Verification Interoperable (PIV-I) Cards
  - **Last bullet:** No _“Federal”_ in actual document.
-  Bottom of page cross-links: 
    - Edit “System Notifications” to _“System Changes and Notifications”_

#### Possible Solution:

Update link text and/or titles where needed. 

#### Link to the Content Page for Contributors: 

[https://playbooks.idmanagement.gov/fpki/](https://playbooks.idmanagement.gov/fpki/)

**Comment by JBPayne007** [comment]
Please talk with Max for best course of action.

**Comment by claytonjbarnette** [comment]
@maxwellfunk let me know how you want me to proceed.

**Comment by maxwellfunk** [comment]
@claytonjbarnette, see the following responses

- The second bullet: title varies from the actual document title: Common Policy X.509 Certificate and Certificate Revocation List (CRL) Profiles NOT X.509 Certificate and CRL Profiles for the U.S. Federal PKI Common Policy Framework
-- you can change to the link title if you wish, its just easier for folks to differentiate policy from profiles when stated up front (to me this is semantic as long as the link goes to the appropriate document)
- Fourth bullet: goes to “Federal Public Key Infrastructure (PKI) X.509 Certificate and CRL Extensions Profile” but text says “X.509 Certificate and CRL Extensions Profile for the FBCA”
-- we are in the process of doing a major update here, the full new title was changed to "Federal Bridge Certification Authority (FBCA) X.509 Certificate and CRL Extensions Profile"... so the next update to the document (which should be published within a month), again semantic
- Fifth bullet: Full title is NOT reflected in the bullet text. Full title is "X.509 Certificate and Certificate Revocation List (CRL) Extensions Profile for Personal Identity Verification Interoperable (PIV-I) Cards
-- this document will actually be tombstoned/retired when the FBCA profiles are updated (within the next month) as we consolidated the PIV-I certificate profile worksheets into that document 
- Last bullet: No “Federal” in actual document.
-- you can update the link title if you want, OMB's oversight is limited to Federal programs/systems

**Comment by claytonjbarnette** [comment]
@maxwellfunk  👍

**Comment by claytonjbarnette** [comment]
✅ - The second bullet: title varies from the actual document title: Common Policy X.509 Certificate and Certificate Revocation List (CRL) Profiles NOT X.509 Certificate and CRL Profiles for the U.S. Federal PKI Common Policy Framework
-- you can change to the link title if you wish, its just easier for folks to differentiate policy from profiles when stated up front (to me this is semantic as long as the link goes to the appropriate document)

✅ - Last bullet: No “Federal” in actual document.
-- you can update the link title if you want, OMB's oversight is limited to Federal programs/systems
