### ISSUE TITLE
Update for the Personal Identity Verification Page

### ISSUE THREAD

**Issue by claytonjbarnette** [GSA/playbooks-wdsv2#640]
#### Description of Issue: ####
Text and Link updates needed for consistency and correctness 

#### Details of Issue: ####
- **[In Introduction](https://playbooks.idmanagement.gov/piv/)**
  - Link is fine but suggest using full term -- Physical Access Control System Guide – rather than PACS Guide.
- In **[“What Is PIV?”](https://playbooks.idmanagement.gov/piv/#what-is-piv)** change title to “What Is a PIV Credential?” based on opening sentence. Change title in page footer, too.
- In **[“Why Is PIV Usage Important?”](https://playbooks.idmanagement.gov/piv/#why-is-piv-usage-important)**
  - Change “individuals that” to “individuals who” x2
  - Remove extra `em` dash in second paragraph
- In **[“Where Can I Find the Standards?”](https://playbooks.idmanagement.gov/piv/#where-can-i-find-the-standards)** 
  - NIST is incorrectly expanded. It is NOT National Institute for Science and Technology (NIST) website. It is National Institute of Standards and Technology (NIST) website. Link itself is fine.
  - FIPS-201 link needs to be updated. First, there should NOT be a hyphen between FIPS and 201. Second, the link should direct reader to FIPS 201-3. Third, this link does NOT go to the document itself but to a NIST Publications page.
  - Links for SP 800-73 and SP 800-76 do NOT go to the documents themselves but to a NIST Publications page.
- **In page footer,** “_Basics of a PIV”_ is used, too, but linked text reads _“PIV Overview”_
- In **[“PIV Overview”](https://playbooks.idmanagement.gov/piv/basics/)** under “Electronic Features”
  -  in bullet “PIV Authentication,” change “which is a certificate and key pair and can be used to verify” to “which is a certificate and key pair that can be used to verify”
  -  in bullet “Digital Signature,” change “, which is a certificate and key pair allows YOU to digitally sign” to “, which is a certificate and key pair that allows YOU to digitally sign.”
  -  in bullet “Encryption,” change second “and” in “, which is a certificate and key pair and allows YOU to digitally encrypt” to “that”
  -  In “PIV Overview” footer, there is no “Basics of a PIV.” It is “PIV Overview.”
- In **[“Getting Started Using a PIV”](https://playbooks.idmanagement.gov/piv/gettingstarted/)** 
  -  under “Middleware,” the table seems extremely out of date.
  -  under “Next Steps,” the link uses the terminology “PIV Details” while the linked section uses “Details” and the footer uses “Details of a PIV.” Very inconsistent.
  -  **In footer:** the word “definitions” in “Middleware definitions” should be capitalized (Middleware Definitions)
- In **[“Details”](https://playbooks.idmanagement.gov/piv/details/)**
  -  under “View Your PIV Credential Certificates” the table is outdated relative to Internet Explorer. Also, inconsistent capitalization of Steps.
  -  under “Understand PIV Certificates” link uses “Basics of a PIV Credential” while linked text says “PIV Overview”
  -  under “Understand PIV Certificates” link uses “Federal Public Key Infrastructure page” but page title is “FPKI Policy and Compliance Audit”
  -  in footer, reader is referred to “Identifiers in a PIV” but actual page title is “Identifiers
- In **[“Certificate Trust”](https://playbooks.idmanagement.gov/piv/cert-trust/)** 
  -  under “Trust” the link “Federal Public Key Infrastructure (FPKI)” actual links to the page titled “FPKI Policy and Compliance Audit.” Should it link to “Federal Public Key Infrastructure Guide Introduction”?
  -  under “Certificate Chains” it appears as though “G2” should be part of the expansion for COMMON. See italicized text in “Trust” as well as blue display box “Federal PKI Person Root – COMMON”
  -  under “Download Root and Intermediate Certificates” the link “the FPKI guide on the Federal Common Policy G2 Update” is confusing. Should it be to the Policies and Standards on that page?
  -  under “Download Any Additional…” the link uses the terminology “Details of a PIV Credential” while the linked section uses “Details” (the footer uses “Details of a PIV”)
  -  In footer, the first entry under “Certificate Trust” should simply read “Trust” not “Certificate Trust”
- In **“[Introduction to Network Authentication Guides](https://playbooks.idmanagement.gov/piv/network/)”** (“Network Authentication” in footer), 
  -  the grammar in the brown display box is in need of editing. Perhaps:

> _Some PIV-based authentication to Microsoft Domain Controllers may have been impacted by the May 2022 Windows server patches. If you encounter these PIV network logon issues, please review the CISA Guidance, which is supported by the following Microsoft Knowledge Base Article page. Additional technical guidance can be requested through **cyberliaison** at cisa.gov_

**Note:** _too, I could not locate any _“cyberliaison”_ on the **CISA** website by search or by reviewing the Contact Us page._

  -  **Footer reads** _“Ports and Protocols”_ while actual title is **“Network Ports and Protocols”**
- In **[“Network Ports and Protocols”](https://playbooks.idmanagement.gov/piv/network/ports/)**
  -   under “Web Services for Validating PIV Certificates” text uses “PIV Authentication certificates” while linked text uses “PIV Credential Certificates”
  -  under “Web Services for the Federal Public Key Infrastructure” 
    - same question as earlier regarding insertion of “G2” in Federal Common Policy Certificate Authority (COMMON) expansion
    - http.fpki.gov is not hyperlinked but URL is questionable.
    - http://http.fpki.gov/fcpca/fcpca.crt is not hyperlinked but following the URL yields an **ERROR** page
- In **[“Domain Controllers” ](https://playbooks.idmanagement.gov/piv/network/dc/)** under “Issue Domain Controller Certificates” the reader is offered a link to tips on the “Local Certification Authority” page. That link works but, in checking the footer links associated with that page (“Local Certification Authority”), the “Auto-Enroll Domain Controllers Using Group Policy Object (GPO)” link that should take the reader to that paragraph doesn’t work.
- In **[“Trust Stores”](https://playbooks.idmanagement.gov/piv/network/trust-stores/)** under “Trusted Root Certification Authorities Trust Store” same “G2” question in COMMON expansion.
- In **[“Account Linking”](https://playbooks.idmanagement.gov/piv/network/account/)** 
  - under “altSecurityIdentities Approach,” the “six options” link does not work.
  - in the green text box “Collaborate with us!” the link to “public scripts authority” yields a “Page not found” error.
  - in page footer clicking on the “Comparing altSecurity Identities and User Principal Name” does not take reader to that paragraph.
- In **[“Network Tuning”](https://playbooks.idmanagement.gov/piv/network/tuning/)** 
  - In opening paragraph, unsure whether email address is operative (email to ICAM-COMMUNITY-TECH at listserv.gsa.gov)
  - Under “Cached Logon Credential Limit” the Microsoft TechNet link works but I don’t see that terminology used on the linked page. Perhaps use “Interactive Logon: Number of Previous Logons to Cache” 
- In **[“Authentication Assurance”](https://playbooks.idmanagement.gov/piv/network/auth/)** page footer, text for next section reads “PIV Auth on macOS” but actual page reads “PIV Authentication on macOS”
- In **[“PIV Authentication on macOS” ](https://playbooks.idmanagement.gov/piv/network/mac/)**
  - in green box, NIST SP 800-53 Identification and Authentication, is not linked to the document.
  - under **[“Choose an Authentication Option”](https://playbooks.idmanagement.gov/piv/network/mac/#choose-an-authentication-option)** link titled “Windows authentication enforcement models” use of “are available in this section of the PIV Playbook” is confusing. Perhaps rewrite to read “Additional details on Windows authentication enforcement models can be found here.” (hyperlink here)
  - under **[“Helpful References“](https://playbooks.idmanagement.gov/piv/network/mac/#helpful-references)** Apple Deployment Guide - Smart card advanced configuration commands” should read “Apple Deployment Guide - Advanced smart card options in macOS”

#### Possible Solution ####
Update and correct where instructed, ask for additional guidance where needed.  

#### Link to the Content Page for Contributors: ####
[https://playbooks.idmanagement.gov/piv/](https://playbooks.idmanagement.gov/piv/)

**Comment by claytonjbarnette** [comment]
@jzepp @SuGhadiali posted this issue from the Link Report Document for your review. Leave a comment if changes or updates are needed.

**Comment by JBPayne007** [comment]
These look good please proceed with corrections after talking with Max for the FICAM links.

**Comment by claytonjbarnette** [comment]
@maxwellfunk for your review, let me know if any adjustments are needed.

**Comment by claytonjbarnette** [comment]
@maxwellfunk following up to see if you have some time to review these updates.

**Comment by maxwellfunk** [comment]
@claytonjbarnette no qualms per our conversation.  Common should be replaced with G2 wherever possible.

**Comment by claytonjbarnette** [comment]
Updates Live, closing ticket
