### ISSUE TITLE
Update CPCT instructions

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/playbooks-wdsv2#643]
#### Description of Issue: ####
GSA has determined that CPCT will no longer be hosted in cloud.gov for public access.  Instead it will be consolidated in a docker image in order to be run locally by interested parties.

#### Details of Issue: ####
We will need to update instructions on how to get to and run the migrated tool, once the docker image is completed.

#### References (Docs, Links, Files): ####
The primary playbooks page this impacts is:
https://playbooks.idmanagement.gov/fpki/tools/cpct/

We will need to reference the CPCT github repo:
https://github.com/GSA/fpkilint

#### Possible Solution ####
Note - this update has a dependency on the docker image build

#### If a New Page or Content is Needed, Expected Outcomes: ####
New instructions or links to the updated repo's wiki will need to be incorporated.

**Comment by maxwellfunk** [comment]
@claytonjbarnette

**Comment by claytonjbarnette** [comment]
@maxwellfunk 
Once the Docker build is complete and new instructions are crafted/approved, I will incorporate the new information onto the [GSA Certificate Profile Conformance Tools](https://playbooks.idmanagement.gov/fpki/tools/cpct/) page, once received. 👍

**Comment by maxwellfunk** [comment]
@claytonjbarnette i think this is now closed now since the updated instructions for docker desktop are in production, correct?

**Comment by claytonjbarnette** [comment]
@maxwellfunk  Correct... closing it.
