### ISSUE TITLE
Update Treasury Information in Common G2 Migration Guide.

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#653]
The “US Treasury Root CA” which has a listed expiration date of 8/14/22.

Link: https://playbooks.idmanagement.gov/fpki/common/certificates/#certificates-issued-by-the-federal-common-policy-ca-g2

**Comment by techliaison** [comment]
should there be a new playbook that just keeps the relevant parts of the Common G2 migration?
For example keep the certs & cert bundles up to date or even just point people to an updated p7b that could be created from the graph if it only contained the certs with a path to Common and a separate p7b for those that only create a path to other roots?
Keep the instructions about configuring various unmanaged systems (from the FAQs)

**Comment by claytonjbarnette** [comment]
@idmken anything I need to do here?
