### ISSUE TITLE
AltSecID Script Link is Bad

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#691]
Page - https://playbooks.idmanagement.gov/piv/network/account/

Correct link - https://github.com/GSA/ficam-scripts-public/tree/master/_altSecId

**Comment by claytonjbarnette** [comment]
**Link Updated:** 
https://playbooks.idmanagement.gov/piv/network/account/#transitioning-from-upn-mapping-to-altsecurityidentities-mapping

@SuGhadiali 
Closing.
