### ISSUE TITLE
Privileged Identity Playbook

### ISSUE THREAD

**Issue by ghost** [GSA/playbooks-wdsv2#738]

**Comment by claytonjbarnette** [comment]
Summited PR: https://github.com/GSA/ficam-playbooks/pull/735

@JBPayne007 [pam](https://playbooks.idmanagement.gov/playbooks/pam/) document not touched, only navigation text updated, let me know if document versioning is still required.

**Comment by idmken** [comment]
fixed #735

**Comment by claytonjbarnette** [comment]
@idmken 👍
