### ISSUE TITLE
Digital Identity Risk Assessment Playbook

### ISSUE THREAD

**Issue by ghost** [GSA/playbooks-wdsv2#744]
#### Details of Issue:
•	Acknowledgments is misspelled. ("e" improperly added after "g")

•	The entry for NIST Special Publication 800-53, Revision 4, [Security and Privacy Controls for Federal Information Systems and Organizations](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r4.pdf), April 2013; Updated January 22, 2015 is outdated. It needs to be updated to NIST Special Publication 800-53, Revision 5, [Security and Privacy Controls for Information Systems and Organizations](https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final), September 2020.

•	NIST Special Publication 800-53A, Revision 4, [Assessing Security and Privacy Controls in Federal Information Systems and Organizations: Building Effective Security Assessment Plans](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53Ar4.pdf), July 2008; Updated December 18, 2014 was superseded. Correct reference should be to NIST Special Publication 800-53A, Revision 5, [Assessing Security and Privacy Controls in Information Systems and Organizations](https://csrc.nist.gov/publications/detail/sp/800-53a/rev-5/final), January 2022.

**Comment by ghost** [comment]
https://playbooks.idmanagement.gov/playbooks/dira/

**Comment by claytonjbarnette** [comment]
@jzepp  corrected word usage *Acknowledgments* in first heading. Interesting read on usage in [North America vs UK](https://grammar.yourdictionary.com/grammar/vs/acknowledgement-vs-acknowledgment). 

- ficam-playbooks/_playbooks/playbook-dira.md ✔️  

According to my editor, there were 21 other places on Playbooks where the UK version is used across 3 files.
- ficam-playbooks/_data/overlay_pam.yml ✔️  (1 instances)
- ficam-playbooks/_playbooks/playbook-dw.md ✔️  (18 instances)
- ficam-playbooks/_playbooks/playbook-pam.md ✔️  (2 instances)

I updated those instances as well and versioned the files where needed. 

**Legend:** ✔️ = Fixed
