### ISSUE TITLE
Federal ICAM Architecture 

### ISSUE THREAD

**Issue by ghost** [GSA/playbooks-wdsv2#746]
#### Details of Issues: 

1. In https://playbooks.idmanagement.gov/arch/standards/ under "Laws," the link to US Code is the 2012 version (https://www.govinfo.gov/content/pkg/USCODE-2012-title5/pdf/USCODE-2012-title5-partI-chap5-subchapII-sec552a.pdf). A 2018 version is available.

2. In https://playbooks.idmanagement.gov/arch/standards/, under "Standards," [NIST SP 800-53A Rev. 4: Assessing Security and Privacy Controls in Federal Information Systems and Organizations - Building Effective Security Assessment Plans](https://csrc.nist.gov/publications/detail/sp/800-53a/rev-4/final) (PDF, December 2014) was superseded by NIST SP 800-53A Rev. 5.

3. In https://playbooks.idmanagement.gov/arch/standards/, under "Standards," [FIPS 201-2: PIV of Federal Employees and Contractors](https://csrc.nist.gov/publications/detail/fips/201/2/final) (PDF, August 2013) was superseded by FIPS 201-3.

#### Possible Solutions: 

1. Link to the 2018 version: https://www.govinfo.gov/content/pkg/USCODE-2018-title5/pdf/USCODE-2018-title5-partI-chap5-subchapII-sec552a.pdf

2. Replace with latest version:
    [NIST SP 800-53A Rev. 5: Assessing Security and Privacy Controls in Information Systems and Organizations](https://csrc.nist.gov/publications/detail/sp/800-53a/rev-5/final) (PDF, January 2022)
   
   Also, replace last sentence of accompanying text with:
   The assessment procedures, executed at various phases of the system development life cycle, are consistent with the security and privacy controls in NIST Special Publication 800-53, Revision 5. 

3. Replace with latest version:
   [FIPS 201-3: Personal Identity Verification (PIV) of Federal Employees and Contractors](https://csrc.nist.gov/publications/detail/fips/201/3/final) (PDF, January 2022)

**Comment by claytonjbarnette** [comment]
@jzepp

✔️  1. Updated with new link and link text (did not see a month, listed only year) 
✔️  2. Updated link, link text, and last sentence
✔️  3. Updated link and link text

@SuGhadiali
