### ISSUE TITLE
PACS Playbook

### ISSUE THREAD

**Issue by ghost** [GSA/playbooks-wdsv2#753]
#### Details of Issue: #### Reference to

1. [The Risk Management Process for Federal Facilities: An Interagency Security Committee Standard](https://www.dhs.gov/isc-policies-standards-best-practices) takes the user to a page where various publications can be found rather than to the precise report cited.
2. NIST [SP 800-116, Revision 1](https://csrc.nist.gov/publications/detail/sp/800-116/rev-1/final), A Recommendation for the Use of PIV Credentials in Physical Access Control Systems (PACS) uses an incorrect report title.
3. In the bulleted list that follows, FIPS 201-2 is cited. It has been superseded by FIPS 201-3

#### Possible Solution ####  

1. Change the link as follows: [The Risk Management Process for Federal Facilities: An Interagency Security Committee Standard](https://www.cisa.gov/sites/default/files/publications/The%20Risk%20Management%20Process%20-%202021%20Edition_2.pdf)
2. Change the report title as follows: NIST [SP 800-116, Revision 1](https://csrc.nist.gov/publications/detail/sp/800-116/rev-1/final), Guidelines for the Use of PIV Credentials in Facility Access.
3. Change the text and link as follows: Use non-deprecated authentication mechanisms, as defined by [FIPS 201-3](https://csrc.nist.gov/publications/detail/fips/201/3/finall).

**Comment by claytonjbarnette** [comment]
**Updates:**  

1. Updated link to `Risk Management Process...` link to: `https://www.cisa.gov/sites/default/files/publications/The%20Risk%20Management%20Process%20-%202021%20Edition_2.pdf`
2. Changed link text to:  _Guidelines for the Use of PIV Credentials in Facility Access_
3. Changed link title and link to: `FIPS 201-3` and `https://csrc.nist.gov/publications/detail/fips/201/3/finall`

@jzepp
