### ISSUE TITLE
PACS Playbook #2

### ISSUE THREAD

**Issue by ghost** [GSA/playbooks-wdsv2#754]
#### Description of Issue: #### 

1. In the PACS Playbook (https://playbooks.idmanagement.gov/pacs/) under Aligning Facility Security Level (FSL) and Authentication (https://playbooks.idmanagement.gov/pacs/alignfslandauth/) in the section titled Assess Facility Security Level (https://playbooks.idmanagement.gov/pacs/alignfslandauth/#assess-facility-security-level) the first blue textbox contains an outdated reference. The same issue occurs in second blue textbox.

2. In the PACS Playbook (https://playbooks.idmanagement.gov/pacs/) under under Aligning Facility Security Level (FSL) and Authentication (https://playbooks.idmanagement.gov/pacs/alignfslandauth/) in the section titled Select Authentication Mechanisms (https://playbooks.idmanagement.gov/pacs/alignfslandauth/#select-authentication-mechanisms) the blue textbox has an outdated link.

3. In the PACS Playbook (https://playbooks.idmanagement.gov/pacs/) under Standards, Policies, and Guidance (https://playbooks.idmanagement.gov/pacs/standards/) under Standards (https://playbooks.idmanagement.gov/pacs/standards/#standards) there's an outdated reference to FIPS 201-2.

4. In the PACS Playbook (https://playbooks.idmanagement.gov/pacs/) under Standards, Policies, and Guidance (https://playbooks.idmanagement.gov/pacs/standards/) under Guidance and Best Practices (https://playbooks.idmanagement.gov/pacs/standards/#guidance-and-best-practices) there is a broken link

#### Details of Issue: ####

1. In both instances, the current link [The Risk Management Process for Federal Facilities: An Interagency Security Committee Standard](https://www.dhs.gov/isc-policies-standards-best-practices) takes the user to a 2016 edition when a 2021 edition is available.

2. FIPS 201-2 has been superseded by FIPS 201-3.

3. FIPS 201-2 has been superseded by FIPS 201-3. 

4. Clicking on [Personal Identity Verification Interoperability for Issuers](https://www.idmanagement.gov/docs/fpki-pivi-for-issuers.pdf), Version 2.0.1, July 27, 2017 yield a Page Not Found Error.

#### Possible Solution ####

1. Change both instances as follows: [The Risk Management Process for Federal Facilities: An Interagency Security Committee Standard](https://www.cisa.gov/sites/default/files/publications/The%20Risk%20Management%20Process%20-%202021%20Edition_2.pdf)

2. Change entry as follows: [FIPS 201-3](https://csrc.nist.gov/publications/detail/fips/201/3/final), Personal Identity Verification (PIV) of Federal Employees and Contractors

3. Change entry as follows: [FIPS 201-3, Personal Identity Verification (PIV) of Federal Employees and Contractors](https://csrc.nist.gov/publications/detail/fips/201/3/final), NIST, January 2022

4. Change link to [Personal Identity Verification Interoperability for Issuers]( https://www.idmanagement.gov/docs/archived/fpki-pivi-for-issuers.pdf), Version 2.0.1, July 27, 2017

**Comment by claytonjbarnette** [comment]
**Updates:** 

1. Updated both instances of link to `https://www.cisa.gov/sites/default/files/publications/The%20Risk%20Management%20Process%20-%202021%20Edition_2.pdf`
2. Update link to: `https://csrc.nist.gov/publications/detail/fips/201/3/final` and following text to: `FIPS 201-3`.
3. Updated link to: `https://csrc.nist.gov/publications/detail/fips/201/3/final` and link text to: `FIPS 201-3, _Personal Identity Verification (PIV) of Federal Employees and Contractors`.
4. Updated link to: `https://www.idmanagement.gov/docs/archived/fpki-pivi-for-issuers.pdf ` and following text to: ` Version 2.0.1, July 27, 2017`

@jzepp
