### ISSUE TITLE
FPKI announcement for new CPCT release version

### ISSUE THREAD

**Issue by maxwellfunk** [GSA/playbooks-wdsv2#765]
#### Description of Issue: ####
the FPKIPA voted to update the Common profiles to v2.2 in October, the CPCT tool needed to be updated to account for the changes to the profiles document.

#### Details of Issue: ####
an announcement needs to be generated on the FPKI announcements in order to advertise the new version and link users to the update instructions.

#### References (Docs, Links, Files): ####

https://playbooks.idmanagement.gov/fpki/tools/cpct/
https://github.com/GSA/cpct-tool/wiki/Rerunning-the-CPCT-Tool-Installer
https://github.com/GSA/cpct-tool/wiki/Updating-the-CPCT-Tool

#### Possible Solution ####
update announcements with link to the updating CPCT wiki page above
https://playbooks.idmanagement.gov/fpki/announcements/

**Comment by claytonjbarnette** [comment]
@maxwellfunk 👍
