### ISSUE TITLE
Update linked version of CPCT Tool

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#771]
For easier maintenance, the link on https://playbooks.idmanagement.gov/fpki/tools/cpct/#accessing-the-cpct-application

should be on the releases page. The direct version link, needs to be updated with every new version. 

## Current text
3. Next, copy and paste the link below in your web browser. The cpct-tool.zip folder will download. It can be located in the device’s Downloads folder as indicated in the screenshot below.

Link: https://github.com/GSA/cpct-tool/archive/refs/tags/v1.0.0.zip

## Proposed text
3. Next, copy and paste the link below in your web browser. Download the zip file of the latest released version. It can be located in the device’s Downloads folder as indicated in the screenshot below.

Link: https://github.com/GSA/cpct-tool/releases

**Comment by claytonjbarnette** [comment]
@idmken 👍

**Comment by claytonjbarnette** [comment]
👍
