### ISSUE TITLE
Sticky Nav not Sticky

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#853]
**Describe the bug**
The side navigation is no longer sticky. It doesn't scroll with the page.

**To Reproduce**
1. Go to any page with side navigation
2. Scroll up and down.
3. The side navigation does not follow.

**Expected behavior**
The side navigation scrolls with the page.

**Desktop (please complete the following information):**
 - OS: MacOS 13.2
 - Browser Edge and Chrome

**Additional context**
Maybe broken when upgraded to USWDS 3.0.

Sticky nav was incorporated from this page - https://github.com/18F/uswds-jekyll

**Comment by idmken** [comment]
Verified sticky side navigation broke with #825

**Comment by claytonjbarnette** [comment]
Sticky now working on both sites(IDM, Playbooks), closing issue. 

@SuGhadiali
