### ISSUE TITLE
Examples of PIV Agreement

### ISSUE THREAD

**Issue by idmken** [GSA/playbooks-wdsv2#920]
#### Description of Issue: ####
Email question - We are in the process of updating our PIV acceptance/agreement form. Are there an examples available?

#### Details of Issue: ####
Provide either links or examples of a PIV agreement form.

#### References (Docs, Links, Files): ####
Digital Certificate user agreement - https://playbooks.idmanagement.gov/playbooks/autopen/#appendix-c-templates
USAccess acknowledgment - https://ack.usaccess.gsa.gov/acknowledgement/activation.aspx
DoD PKI Certificate Acceptance DD From 2842 - https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd2842.pdf

#### Possible Solution ####
List examples on one of these pages with some text
https://playbooks.idmanagement.gov/piv/basics/

**Comment by claytonjbarnette** [comment]
@idmken  will the below content work for the bottom of the `piv/basics/` page. 

## Example  Forms

Provided below are links to example forms you can use as templates to create or update your own PIV acceptance and agreement forms.

- [Digital Certificate user agreement](https://playbooks.idmanagement.gov/playbooks/autopen/#appendix-c-templates)
- [USAccess acknowledgment](https://ack.usaccess.gsa.gov/acknowledgement/activation.aspx)
- [DoD PKI Certificate Acceptance DD From 2842](https://www.esd.whs.mil/Portals/54/Documents/DD/forms/dd/dd2842.pdf)

**Comment by idmken** [comment]
#936
