### ISSUE TITLE
New Playbook for Windows Hello (WHfb)

### ISSUE THREAD

**Issue by claytonjbarnette** [GSA/playbooks-wdsv2#929]
### Description
The purpose of this playbook is to guide administrators through planning, configuring, testing, and implementing Windows Hello for Business (WHfB). WHfB offers two-factor authentication by combining user credentials tied to a device with a biometric or a personal identification number (PIN).

### Audience/ Use Cases
- System Admin at a federal agency

### Takeaways
- Step-by-step guide for configuring and implementing WHfB in a cloud only environment.

### Future Location
- TBD

**Comment by idmken** [comment]
#936 and #933
